-- FOOD_ID 를 입력하면 FOOD_NAME을 반환하는 함수

create or replace FUNCTION FN_GET_FOOD_NAME (SET_FOOD_ID NUMBER) 
    RETURN VARCHAR2 IS V_FOOD_NAME VARCHAR2(100); 
BEGIN 
    SELECT FOOD_NAME
      INTO V_FOOD_NAME 
      FROM FOOD 
     WHERE FOOD_ID = SET_FOOD_ID; 

    RETURN V_FOOD_NAME; 
END;

