--------------------------------------------------------
CREATE USER student IDENTIFIED BY student;
GRANT connect,resource TO student;
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------
DROP TABLE MEMBER CASCADE CONSTRAINT;
  CREATE TABLE "STUDENT"."MEMBER" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"GENDER" CHAR(1 BYTE), 
	"AGE" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PHONE" CHAR(11 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"HOBBY" VARCHAR2(50 BYTE), 
	"ENROLLDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STUDENT.MEMBER
SET DEFINE OFF;
Insert into STUDENT.MEMBER (USERID,PASSWORD,USERNAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLLDATE) values ('user11','user11','유재석','M',1,'1111@naver.com','12312341111','서울시영등포구 당산로','독서,운동,등산,그림,요리',to_date('17/11/13','RR/MM/DD'));
Insert into STUDENT.MEMBER (USERID,PASSWORD,USERNAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLLDATE) values ('user22','user22','이효리','F',18,'123@nate.com','0105464845 ','서울시 강남','독서,운동,등산',to_date('17/09/28','RR/MM/DD'));
Insert into STUDENT.MEMBER (USERID,PASSWORD,USERNAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLLDATE) values ('admin','admin','관리자','F',45,'admin@naver.com','01012345678','경기도 수원시 팔달구','독서,운동,등산',to_date('16/03/15','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007005
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."SYS_C007005" ON "STUDENT"."MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "STUDENT"."MEMBER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENT"."MEMBER" ADD CHECK (GENDER IN ('M','F')) ENABLE;
  ALTER TABLE "STUDENT"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."MEMBER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);